# No personal credit.
# Taken from here and adapted:
# https://github.com/wekan/wekan/blob/master/docker-compose.yml
version: '2'
services:
  wekandb:
    image: mongo:4.4
    container_name: wekan-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: quay.io/wekan/wekan:v6.11
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    ports:
      - 9888:8080
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=https://localhost
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
      - DEBUG=false
      - ORACLE_OIM_ENABLED=false
      - OAUTH2_ENABLED=false
      - OAUTH2_LOGIN_STYLE=redirect
    depends_on:
      - wekandb
volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge
