FROM concafe/wekan-cli:integration
COPY e2e .
RUN chmod +x entrypoint.sh && \
    mkdir /log && \
    touch /log/stdout.log && \
    touch /log/stderr.log
ENV WEKAN_URL=wekan-e2e-app:8080
ENV WEKAN_USER=testuser
ENV WEKAN_PWD=testuser123
CMD ["./entrypoint.sh"]
