FROM rust:1.61

WORKDIR /usr/src/myapp
COPY crates .
WORKDIR /usr/src/myapp/wekan-cli
RUN cargo install --features integration --path .
RUN chmod +x e2e/entrypoint.sh && \
    mkdir /log && \
    touch /log/stdout.log && \
    touch /log/stderr.log
CMD ["wekan-cli"]
