name: All in one

on:
  push:
    branches: [ "main" ]
    workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  all:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'All in one (save compilation)'
      run: |
        cargo fmt -- --check && cargo clippy -- -Dwarnings && \
        cargo test && cargo build && \
        cargo test --features wekan-cli/store && \
        cargo clippy --features wekan-cli/store -- -Dwarnings
        cargo build --features wekan-cli/store
